# Generated by Django 4.1.6 on 2023-02-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt_time', models.DateTimeField(auto_now_add=True)),
                ('end_dt_time', models.DateTimeField(auto_now_add=True)),
                ('examination_room', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_floor', models.IntegerField()),
                ('block_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('registered', models.BooleanField(default=True)),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('insurance_id', models.TextField()),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.TextField()),
                ('unavailable', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospital_django.block')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hospital_django.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hospital_django.room')),
            ],
        ),
        migrations.CreateModel(
            name='Undergo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assisting_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergoes', to='hospital_django.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergoes', to='hospital_django.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergoes', to='hospital_django.physician')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergoes', to='hospital_django.procedure')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergoes', to='hospital_django.stay')),
            ],
        ),
        migrations.CreateModel(
            name='Trained_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(auto_now_add=True)),
                ('certification_exp', models.DateField(auto_now_add=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_ins', to='hospital_django.physician')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_ins', to='hospital_django.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dose', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribes', to='hospital_django.appointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribes', to='hospital_django.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribes', to='hospital_django.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribes', to='hospital_django.physician')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital_django.physician'),
        ),
        migrations.CreateModel(
            name='On_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_call_start', models.DateTimeField(auto_now_add=True)),
                ('on_call_end', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_calls', to='hospital_django.block')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_calls', to='hospital_django.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospital_django.physician')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital_django.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital_django.physician'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prep_nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital_django.nurse'),
        ),
        migrations.CreateModel(
            name='Affiliated_with',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_affiliation', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_withs', to='hospital_django.department')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_withs', to='hospital_django.physician')),
            ],
        ),
    ]
