# Generated by Django 4.1.6 on 2023-02-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_dt_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_dt_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='on_call',
            name='on_call_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stay',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trained_in',
            name='certification_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trained_in',
            name='certification_exp',
            field=models.DateField(),
        ),
    ]
